# Generated by Django 4.2.9 on 2024-01-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=100)),
                ('action_flag', models.PositiveIntegerField()),
                ('change_message', models.TextField()),
            ],
        ),
    ]
