# Generated by Django 4.2.9 on 2024-01-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_rename_action_time_backup_download_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='download_date',
            field=models.DateTimeField(),
        ),
    ]
