# Generated by Django 4.2.9 on 2024-01-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_alter_backup_download_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='download_date',
            field=models.DateField(),
        ),
    ]
