# Generated by Django 4.2.7 on 2023-12-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Staff_Salary_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rent_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Due_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerFee',
        ),
        migrations.DeleteModel(
            name='DueFee',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
        migrations.DeleteModel(
            name='StaffSalary',
        ),
    ]
