# Generated by Django 4.2.7 on 2023-12-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customer_weight'),
        ('accounts', '0002_accounts_delete_customerfee_delete_duefee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
