# Generated by Django 4.2.7 on 2023-12-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paidaccount_rent_paid_paidaccount_staff_salary_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidaccount',
            old_name='amount_paid',
            new_name='customer_fee_paid',
        ),
    ]
