# Generated by Django 4.2.7 on 2023-12-27 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_customer_id'),
        ('accounts', '0006_rename_amount_paid_paidaccount_customer_fee_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
