# Generated by Django 4.2.7 on 2023-12-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_paidaccount_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
