# Generated by Django 4.2.7 on 2023-12-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounts_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='Due_Amount',
        ),
    ]
