# Generated by Django 4.2.7 on 2023-12-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_accounts_due_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paidaccount',
            name='customer',
        ),
        migrations.AddField(
            model_name='accounts',
            name='customer_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidaccount',
            name='customer_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidaccount',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
