# Generated by Django 4.2.7 on 2024-01-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_proffit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
