# Generated by Django 4.2.7 on 2024-01-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_remove_rent_description_remove_salary_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='daily_proffit',
            new_name='daily_profit',
        ),
    ]
