# Generated by Django 4.2.7 on 2023-12-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=500)),
                ('workout_name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('exercises_name', models.CharField(max_length=200)),
                ('sets', models.CharField(max_length=50)),
                ('reps', models.CharField(max_length=50)),
            ],
        ),
    ]
