# Generated by Django 4.2.7 on 2024-01-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='customer_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
