# Generated by Django 4.2.7 on 2023-12-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_customer_id_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bmi',
        ),
        migrations.AddField(
            model_name='customer',
            name='height_in_inches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='heightinfeet',
            field=models.IntegerField(default=0),
        ),
    ]
