# Generated by Django 4.2.7 on 2023-12-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_bmi_customer_height_in_inches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bmi',
            field=models.FloatField(default=0),
        ),
    ]
