# Generated by Django 4.2.7 on 2023-12-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
