# Generated by Django 4.2.7 on 2023-12-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='height_in_inches',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='heightinfeet',
        ),
        migrations.AddField(
            model_name='customer',
            name='height_feet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='height_inches',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
