# Generated by Django 4.2.7 on 2023-12-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
