# Generated by Django 4.2.7 on 2023-12-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customer_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
