# Generated by Django 4.2.9 on 2024-01-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='goal',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
