# Generated by Django 4.2.9 on 2024-01-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_databasebackupformanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasebackupformanager',
            old_name='backup_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='databasebackupformanager',
            old_name='backup_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='databasebackupformanager',
            name='backup_name',
        ),
    ]
