# Generated by Django 4.2.9 on 2024-01-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_backup_date_databasebackupformanager_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataBaseBackupForManager',
        ),
    ]
