# Generated by Django 4.2.7 on 2023-12-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='Instructor_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='managerassistant',
            name='ManagerAssistant_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
