# Generated by Django 4.2.7 on 2023-12-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_manager', '0003_delete_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerassistant',
            name='email',
        ),
    ]
