# Generated by Django 4.2.7 on 2024-01-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_manager', '0004_remove_managerassistant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructor_phone_no', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('timings', models.TimeField()),
            ],
        ),
    ]
