# Generated by Django 4.2.7 on 2024-01-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_manager', '0005_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_ID',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
