# Generated by Django 4.2.7 on 2024-01-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_manager', '0006_instructor_instructor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='timings',
            field=models.CharField(max_length=50),
        ),
    ]
